#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X D

bspc config border_width         1
bspc config window_gap           1.25

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

